// telemetry.proto — контракт данных между агентом и сервером.
//
// ПОЧЕМУ Protocol Buffers (protobuf), а не JSON?
// 1. Размер: protobuf в 3-10 раз компактнее JSON (критично при 20+ станках × 1 запись/сек)
// 2. Скорость: бинарная сериализация — нет парсинга строк, нет кавычек, нет пробелов
// 3. Типизация: схема описывает типы полей ЯВНО — string не пролезет вместо double
// 4. Совместимость: можно добавить новое поле, не ломая старых клиентов
//    (критично в air-gap контуре, где агент и сервер обновляются НЕ одновременно)
// 5. Кодогенерация: из одного .proto файла генерируются клиент и сервер
//    на Go, Python, Java и т.д. — один источник правды
//
// КОГДА JSON лучше?
// - Отладка руками (JSON читаем, protobuf — нет)
// - Публичные REST API (protobuf редко используют снаружи)
// - У нас внутренний сервис → protobuf идеален

// syntax = "proto3" — версия синтаксиса protobuf.
// proto3 vs proto2:
// - proto3 проще: нет required/optional (все поля optional по умолчанию)
// - proto3 убрал дефолтные значения — поле с нулевым значением не сериализуется
//   (экономия трафика)
// - proto3 — текущий стандарт, proto2 используют только в legacy-проектах

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: telemetry.proto

// package определяет пространство имён в protobuf.
// Не путать с go_package — это для protobuf-совместимости между языками.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetryService_Ingest_FullMethodName          = "/telemetry.TelemetryService/Ingest"
	TelemetryService_StreamTelemetry_FullMethodName = "/telemetry.TelemetryService/StreamTelemetry"
)

// TelemetryServiceClient is the client API for TelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TelemetryService — gRPC сервис для приёма телеметрии.
//
// ПОЧЕМУ gRPC, а не REST?
// 1. HTTP/2: мультиплексирование, сжатие headers, бинарный протокол
// 2. Streaming: можно открыть поток и слать данные непрерывно (StreamTelemetry)
// 3. Кодогенерация: клиент и сервер генерируются из .proto — нет расхождений
// 4. Контракт: .proto файл = единый источник правды для всех команд
//
// КОГДА REST лучше?
// - Публичный API для внешних потребителей (браузер, curl)
// - У нас внутренний сервис → gRPC эффективнее
type TelemetryServiceClient interface {
	// Ingest — приём батча телеметрии (unary RPC).
	// Клиент отправляет один запрос, получает один ответ.
	// Используется при отправке накопленных данных из WAL.
	Ingest(ctx context.Context, in *TelemetryBatch, opts ...grpc.CallOption) (*IngestResponse, error)
	// StreamTelemetry — потоковая отправка телеметрии (client streaming).
	// ПОЧЕМУ streaming?
	// В реальном времени агент отправляет данные непрерывно.
	// Без streaming: каждую секунду новый TCP handshake (дорого).
	// С streaming: одно соединение, данные текут непрерывно.
	//
	// client streaming = клиент шлёт поток, сервер отвечает ОДИН раз в конце.
	// Альтернатива: bidirectional streaming — сервер тоже шлёт данные обратно.
	// Нам хватает client streaming: серверу нечего отправлять агенту в процессе.
	StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetryRecord, IngestResponse], error)
}

type telemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryServiceClient(cc grpc.ClientConnInterface) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) Ingest(ctx context.Context, in *TelemetryBatch, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, TelemetryService_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetryRecord, IngestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TelemetryService_ServiceDesc.Streams[0], TelemetryService_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryRecord, IngestResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryService_StreamTelemetryClient = grpc.ClientStreamingClient[TelemetryRecord, IngestResponse]

// TelemetryServiceServer is the server API for TelemetryService service.
// All implementations must embed UnimplementedTelemetryServiceServer
// for forward compatibility.
//
// TelemetryService — gRPC сервис для приёма телеметрии.
//
// ПОЧЕМУ gRPC, а не REST?
// 1. HTTP/2: мультиплексирование, сжатие headers, бинарный протокол
// 2. Streaming: можно открыть поток и слать данные непрерывно (StreamTelemetry)
// 3. Кодогенерация: клиент и сервер генерируются из .proto — нет расхождений
// 4. Контракт: .proto файл = единый источник правды для всех команд
//
// КОГДА REST лучше?
// - Публичный API для внешних потребителей (браузер, curl)
// - У нас внутренний сервис → gRPC эффективнее
type TelemetryServiceServer interface {
	// Ingest — приём батча телеметрии (unary RPC).
	// Клиент отправляет один запрос, получает один ответ.
	// Используется при отправке накопленных данных из WAL.
	Ingest(context.Context, *TelemetryBatch) (*IngestResponse, error)
	// StreamTelemetry — потоковая отправка телеметрии (client streaming).
	// ПОЧЕМУ streaming?
	// В реальном времени агент отправляет данные непрерывно.
	// Без streaming: каждую секунду новый TCP handshake (дорого).
	// С streaming: одно соединение, данные текут непрерывно.
	//
	// client streaming = клиент шлёт поток, сервер отвечает ОДИН раз в конце.
	// Альтернатива: bidirectional streaming — сервер тоже шлёт данные обратно.
	// Нам хватает client streaming: серверу нечего отправлять агенту в процессе.
	StreamTelemetry(grpc.ClientStreamingServer[TelemetryRecord, IngestResponse]) error
	mustEmbedUnimplementedTelemetryServiceServer()
}

// UnimplementedTelemetryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetryServiceServer struct{}

func (UnimplementedTelemetryServiceServer) Ingest(context.Context, *TelemetryBatch) (*IngestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedTelemetryServiceServer) StreamTelemetry(grpc.ClientStreamingServer[TelemetryRecord, IngestResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedTelemetryServiceServer) mustEmbedUnimplementedTelemetryServiceServer() {}
func (UnimplementedTelemetryServiceServer) testEmbeddedByValue()                          {}

// UnsafeTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryServiceServer will
// result in compilation errors.
type UnsafeTelemetryServiceServer interface {
	mustEmbedUnimplementedTelemetryServiceServer()
}

func RegisterTelemetryServiceServer(s grpc.ServiceRegistrar, srv TelemetryServiceServer) {
	// If the following call panics, it indicates UnimplementedTelemetryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetryService_ServiceDesc, srv)
}

func _TelemetryService_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelemetryBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).Ingest(ctx, req.(*TelemetryBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TelemetryServiceServer).StreamTelemetry(&grpc.GenericServerStream[TelemetryRecord, IngestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryService_StreamTelemetryServer = grpc.ClientStreamingServer[TelemetryRecord, IngestResponse]

// TelemetryService_ServiceDesc is the grpc.ServiceDesc for TelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.TelemetryService",
	HandlerType: (*TelemetryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _TelemetryService_Ingest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _TelemetryService_StreamTelemetry_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "telemetry.proto",
}
