// telemetry.proto — контракт данных между агентом и сервером.
//
// ПОЧЕМУ Protocol Buffers (protobuf), а не JSON?
// 1. Размер: protobuf в 3-10 раз компактнее JSON (критично при 20+ станках × 1 запись/сек)
// 2. Скорость: бинарная сериализация — нет парсинга строк, нет кавычек, нет пробелов
// 3. Типизация: схема описывает типы полей ЯВНО — string не пролезет вместо double
// 4. Совместимость: можно добавить новое поле, не ломая старых клиентов
//    (критично в air-gap контуре, где агент и сервер обновляются НЕ одновременно)
// 5. Кодогенерация: из одного .proto файла генерируются клиент и сервер
//    на Go, Python, Java и т.д. — один источник правды
//
// КОГДА JSON лучше?
// - Отладка руками (JSON читаем, protobuf — нет)
// - Публичные REST API (protobuf редко используют снаружи)
// - У нас внутренний сервис → protobuf идеален

// syntax = "proto3" — версия синтаксиса protobuf.
// proto3 vs proto2:
// - proto3 проще: нет required/optional (все поля optional по умолчанию)
// - proto3 убрал дефолтные значения — поле с нулевым значением не сериализуется
//   (экономия трафика)
// - proto3 — текущий стандарт, proto2 используют только в legacy-проектах

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: telemetry.proto

// package определяет пространство имён в protobuf.
// Не путать с go_package — это для protobuf-совместимости между языками.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TelemetryRecord — одно показание с одного станка в один момент времени.
// Это атомарная единица данных в нашей системе.
type TelemetryRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный ID записи для идемпотентности.
	// Агент генерирует UUID ДО отправки. При повторной отправке
	// (at-least-once) сервер видит тот же record_id и делает upsert.
	//
	// ПОЧЕМУ string, а не bytes для UUID?
	// - string читаемее при отладке (можно grep в логах)
	// - Разница в размере минимальна (36 байт string vs 16 байт bytes)
	// - В БД храним как UUID-тип, конвертация тривиальна
	RecordId string `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	// Идентификатор станка: "CNC-01", "LATHE-02" и т.д.
	MachineId string `protobuf:"bytes,2,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	// Время снятия показания.
	// ПОЧЕМУ google.protobuf.Timestamp, а не int64 (unix timestamp)?
	// - Timestamp = секунды + наносекунды (int64 теряет наносекунды или требует конвенцию)
	// - Самодокументируемый: видя Timestamp, разработчик ЗНАЕТ что это время
	// - int64 неоднозначен: это секунды? миллисекунды? микросекунды?
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Показания датчиков.
	// ПОЧЕМУ double, а не float?
	// - double = 64 бита, float = 32 бита
	// - Для промышленных датчиков нужна точность (например, вибрация 0.00342 мм/с)
	// - Разница в трафике = 4 байта на поле — несущественно при 1 записи/сек
	Temperature   float64 `protobuf:"fixed64,4,opt,name=temperature,proto3" json:"temperature,omitempty"` // Температура (°C)
	Vibration     float64 `protobuf:"fixed64,5,opt,name=vibration,proto3" json:"vibration,omitempty"`     // Вибрация (мм/с)
	Pressure      float64 `protobuf:"fixed64,6,opt,name=pressure,proto3" json:"pressure,omitempty"`       // Давление (бар)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRecord) Reset() {
	*x = TelemetryRecord{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRecord) ProtoMessage() {}

func (x *TelemetryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRecord.ProtoReflect.Descriptor instead.
func (*TelemetryRecord) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryRecord) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *TelemetryRecord) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *TelemetryRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TelemetryRecord) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *TelemetryRecord) GetVibration() float64 {
	if x != nil {
		return x.Vibration
	}
	return 0
}

func (x *TelemetryRecord) GetPressure() float64 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

// TelemetryBatch — пакет записей для отправки.
// ПОЧЕМУ батч, а не по одной записи?
//  1. Сетевой overhead: каждый gRPC вызов = TCP handshake + HTTP/2 headers.
//     Отправка 100 записей одним вызовом вместо 100 вызовов — в разы эффективнее.
//  2. Транзакционность: сервер может записать весь батч в БД одной транзакцией.
//  3. Backpressure: если агент копит данные (WAL), он отправляет их батчами
//     при восстановлении связи — не по одной.
//
// РАЗМЕР БАТЧА: обычно 100-1000 записей. Слишком большой батч:
// - Долго сериализуется/десериализуется
// - Если упадёт на середине — все записи потеряны
// - gRPC по умолчанию ограничивает сообщение 4MB
type TelemetryBatch struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Records []*TelemetryRecord     `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	// ID агента-отправителя — для логирования и мониторинга.
	// Если один из 20 агентов отправляет мусор, нужно знать какой именно.
	AgentId       string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryBatch) Reset() {
	*x = TelemetryBatch{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatch) ProtoMessage() {}

func (x *TelemetryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatch.ProtoReflect.Descriptor instead.
func (*TelemetryBatch) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryBatch) GetRecords() []*TelemetryRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *TelemetryBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// IngestResponse — ответ сервера на приём батча.
type IngestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Сколько записей принято. Может быть меньше отправленных,
	// если часть уже была (idempotent upsert).
	AcceptedCount int32 `protobuf:"varint,1,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	// Ошибки по отдельным записям (если есть).
	// ПОЧЕМУ не просто один код ошибки на весь батч?
	// Если из 100 записей 1 невалидна — не нужно отбрасывать остальные 99.
	// Агент перешлёт только проблемные записи.
	Errors        []*RecordError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *IngestResponse) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *IngestResponse) GetErrors() []*RecordError {
	if x != nil {
		return x.Errors
	}
	return nil
}

// RecordError — ошибка обработки конкретной записи.
type RecordError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordError) Reset() {
	*x = RecordError{}
	mi := &file_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordError) ProtoMessage() {}

func (x *RecordError) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordError.ProtoReflect.Descriptor instead.
func (*RecordError) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *RecordError) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *RecordError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\ttelemetry\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x01\n" +
	"\x0fTelemetryRecord\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\tR\tmachineId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x01R\vtemperature\x12\x1c\n" +
	"\tvibration\x18\x05 \x01(\x01R\tvibration\x12\x1a\n" +
	"\bpressure\x18\x06 \x01(\x01R\bpressure\"a\n" +
	"\x0eTelemetryBatch\x124\n" +
	"\arecords\x18\x01 \x03(\v2\x1a.telemetry.TelemetryRecordR\arecords\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\"g\n" +
	"\x0eIngestResponse\x12%\n" +
	"\x0eaccepted_count\x18\x01 \x01(\x05R\racceptedCount\x12.\n" +
	"\x06errors\x18\x02 \x03(\v2\x16.telemetry.RecordErrorR\x06errors\"D\n" +
	"\vRecordError\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9e\x01\n" +
	"\x10TelemetryService\x12>\n" +
	"\x06Ingest\x12\x19.telemetry.TelemetryBatch\x1a\x19.telemetry.IngestResponse\x12J\n" +
	"\x0fStreamTelemetry\x12\x1a.telemetry.TelemetryRecord\x1a\x19.telemetry.IngestResponse(\x01B;Z9github.com/pzmash/iot-platform/internal/transport/grpc/pbb\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_telemetry_proto_goTypes = []any{
	(*TelemetryRecord)(nil),       // 0: telemetry.TelemetryRecord
	(*TelemetryBatch)(nil),        // 1: telemetry.TelemetryBatch
	(*IngestResponse)(nil),        // 2: telemetry.IngestResponse
	(*RecordError)(nil),           // 3: telemetry.RecordError
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_telemetry_proto_depIdxs = []int32{
	4, // 0: telemetry.TelemetryRecord.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: telemetry.TelemetryBatch.records:type_name -> telemetry.TelemetryRecord
	3, // 2: telemetry.IngestResponse.errors:type_name -> telemetry.RecordError
	1, // 3: telemetry.TelemetryService.Ingest:input_type -> telemetry.TelemetryBatch
	0, // 4: telemetry.TelemetryService.StreamTelemetry:input_type -> telemetry.TelemetryRecord
	2, // 5: telemetry.TelemetryService.Ingest:output_type -> telemetry.IngestResponse
	2, // 6: telemetry.TelemetryService.StreamTelemetry:output_type -> telemetry.IngestResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
